### ISSUE TITLE
filter out non-coding mutations before sending to MUPIT

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#122]

**Comment by maryjgoldman** [comment]
Mutation columns have coding and non-coding mutations in them. From the caret menu at the top of the column you can send mutations to our sister group, MUPIT to render the mutations in the column on a 3D protein structure. Right now we are sending both types of mutations. But since MUPIT can only show coding mutations, we want to only send coding mutations.

**Comment by krepecka** [comment]
Could it be possible to get more context (or reference for reading) on how to determine whether mutation is coding or not ? I would like to solve this problem but my knowledge of genetics is lacking a bit.

**Comment by jingchunzhu** [comment]
@krepecka googling around to learn about gene structure, exons, introns, and coding sequences. 
 here is just wikipedia.    https://en.wikipedia.org/wiki/Coding_region . https://en.wikipedia.org/wiki/Gene_structure .  Let us know if you have questions or this is too much biology for you. 

For the mutation column, both the gene structure (gene model) and the mutations' exact position are in the xena "state", you test if a mutation overlaps with the coding region of the gene model.   If it overlaps, the mutation is a coding mutation.

**Comment by maryjgoldman** [comment]
Another way to look at this is that if you look at the gene model at the top of the column (that's the boxes with the lines through them), we want the mutations that overlap with the tallest boxes. Those are the coding mutations.

**Comment by maryjgoldman** [comment]
If a box has both a short and tall part, we only want the mutations that overlap with the tall part. Not the short part.

**Comment by acthp** [comment]
@krepecka Note that we build a spatial index for mutations, for doing fast overlap checking. The algorithm will probably be something like "for each exon, use index to find mutations overlapping exon, and make unique".

If you look at the props going to ```Column``` the index is in ```index.byPosition```. Gene model (exon list) will be in ```data.refGene```. API for overlaps is ```intervalTree.matches```.

Many of the somatic mutation datasets don't include intron mutations, so they won't be useful for testing the filter. The icgc cohort does include intron mutations

https://xenabrowser.net/datapages/?host=https%3A%2F%2Ficgc.xenahubs.net&dataset=SNV.donor.codingMutation-allProjects

After selecting the icgc cohort and somatic mutation dataset, you can view intron mutations using the "Show introns" option on the "..." menu on the column.

**Comment by krepecka** [comment]
Thanks a lot for the help! Will try to produce something meaningful.
