### ISSUE TITLE
check out what is XenaR and http://www.cancergenomics.net/multiomics.html

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#123]

**Comment by souravsingh** [comment]
@jingchunzhu I have installed the package and will be able to give the feedback on the package soon.

**Comment by jingchunzhu** [comment]
@souravsingh great. looking forward to the update.

**Comment by souravsingh** [comment]
I have taken a look at the XenaR package and here is what I think- XenaR is a good client library for UCSC Xena to query various datasets available in UCSC Xena and retrieve them directly in matrix format without preprocessing. It doesn't contain any kind of visualization features that the UCSC Xena client library contains, which can be a bummer.

**Comment by jingchunzhu** [comment]
@souravsingh  Thanks for the summary. It is fine that XenaR does not provide viz (and perhaps a good idea) -- likely it is just serve the function of pulling external public data (in this case on xena) to R environment, and then analysts decide what analysis to run on these data, and use their existing visualization tool or code for viewing their analysis results.

**Comment by souravsingh** [comment]
The library can come really handy for the Pathway Perturbation project since I can query and access the data directly in matrix format.

**Comment by souravsingh** [comment]
@jingchunzhu I will also look into the multiomics tool

**Comment by souravsingh** [comment]
@jingchunzhu The multiomics tool could be handy for the Pathway perturbation since it can identify the paired features between the mRNA and the methylation profiles and the possible interactions.
