### ISSUE TITLE
crosshair with tooltip

### ISSUE THREAD

**Issue by acthp** [ucscXena/ucsc-xena-client#13]

**Comment by achang28** [comment]
Sample image from Production...

![tooltip-crosshair](https://cloud.githubusercontent.com/assets/3760499/13406688/b11e3c22-ded9-11e5-85ce-f1ad65086354.png)

**Comment by achang28** [comment]
I am taking on this issue...

**Comment by achang28** [comment]
Please close this issue if the present solution is acceptable.
