### ISSUE TITLE
color scale for PCAWG cnv data

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#131]

**Comment by maryjgoldman** [comment]
Does this need anything from Brian or is this a data wrangling issue?

**Comment by jingchunzhu** [comment]
data wrangling issue.

**Comment by jingchunzhu** [comment]
sorry not a data wrangling issue. But a coloring issue. backlogged.

**Comment by jingchunzhu** [comment]
resolved.
