### ISSUE TITLE
new column in highlighting/search/zoom/newColumn null data handling needs improvement

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#134]

**Comment by acthp** [comment]
Is this the issue that the inverse of a filter expression will match null? So A:>3 new column will be samples over 3 are true, but samples under 3 OR null are false. I'm not sure there's a  good solution to this, other than filtering nulls first. Perhaps it could be a option when creating the column, to pass nulls through.
