### ISSUE TITLE
pieces (info) needed for building violin plot

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#136]
Kernel Density Estimation  https://bl.ocks.org/mbostock/4341954
Violin/Box plots  http://bl.ocks.org/z-m-k/5014368
----------------------------
Kernel Density Estimation might be used to in conjunction with spline line in highchair to support better histogram in chart mode

**Comment by jingchunzhu** [comment]
https://github.com/asielen/D3_Reusable_Charts/tree/master/distro_chart

**Comment by jingchunzhu** [comment]
https://github.com/jasondavies/science.js

**Comment by syt123450** [comment]
I read the material above, but I found it is not convenient to create a violin from the above blog. So I create a violin chart demo using chart.js and a plugin for chart.js, and as the requirement is not clear enough, I can just create a prototype of the violin plot. 

The link for the demo project is https://github.com/syt123450/violin-chart-sample, the link for live example is https://syt123450.github.io/violin-chart-sample/. 

The  style and violin can be customized, I hope I can develop the violin part for ucsc-xena-client, looking forward for your suggestion.

Thank you.
