### ISSUE TITLE
datapages meta filter gone

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#137]

**Comment by maryjgoldman** [comment]
I was talking to Brian and decided to not re-implement it. It felt like it was confusing to be connected to a hub but not see anything from it. If you want to view what is in a hub, you just click on the hub.

What use case were you using this feature for?

**Comment by jingchunzhu** [comment]
Mary, meta filter was your idea back then, not mine :)  I don't mind it to be gone, definitely have no time to reimplement it.

**Comment by maryjgoldman** [comment]
Oh I forgot that! Great. Thank goodness
