### ISSUE TITLE
change "dynamically subtract mean" in the actual data to "dynamically apply coloring without changing underlining data"

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#138]

**Comment by souravsingh** [comment]
@jingchunzhu I would like to work on the issue. How do I start?

**Comment by NikolayOG** [comment]
@jingchunzhu I would like to work on this issue as well. @souravsingh How can I help you?

**Comment by jingchunzhu** [comment]
@NikolayOG @souravsingh 
suggestion: first know how to use the xena browser app,  pull up some appropriate columns (genomic matrix type of columns), see how the color, tooltip, vizSettings, KM, search, download work. 

the fix would be to drop the normalization code from models/denseMatrix, models/datasetJoins, and models/searchSamples, and instead apply the offset in the color scale, either in heatmapColors, or in models/denseMatrix.

**Comment by jingchunzhu** [comment]
https://github.com/ucscXena/ucsc-xena-client/tree/newDisplaySetting

**Comment by jingchunzhu** [comment]
https://github.com/ucscXena/ucsc-xena-client/pull/165
