### ISSUE TITLE
chart does not save 'Color by' setting when creating a bookmark

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#161]
[This bookmark](https://xenabrowser.net/heatmap/?bookmark=34c9a60b48d4a5a656697aeaf73ce984) is supposed to look like this:

![untitled3](https://cloud.githubusercontent.com/assets/13877333/23806773/dfffb35c-0577-11e7-96d0-4eb2d649fc2a.png)

But instead looks like this:

![untitled5](https://cloud.githubusercontent.com/assets/13877333/23806802/045d075e-0578-11e7-9258-8bc7845d1b5c.png)

**Comment by jingchunzhu** [comment]
fixed https://github.com/ucscXena/ucsc-xena-client/commit/ccf80f3b4de8d767909401db873dee72872d4191
