### ISSUE TITLE
home page needs to be https

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#182]
In October Chrome is going to block requests going from http (which is what our home page is now) to https. Need to make xena.ucsc.edu an https page

**Comment by naman03malhotra** [comment]
@maryjgoldman we need to install SSL certificate for this on the server and change nginx settings
https://letsencrypt.org/ provides free SSL
cc @acthp

**Comment by maryjgoldman** [comment]
@naman03malhotra Thanks for the help and the link!

**Comment by jingchunzhu** [comment]
we will check in on this issue on July 2018.
