### ISSUE TITLE
If gene input doesn't match any data, then label is '[unknown]'

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#185]
This is unhelpful because there is no feedback to help you figure out why there was no data. For instance, did you type the gene name incorrectly? Or did you only misspell your gene name and it actually is in the database?

**Comment by abhishekvermasg** [comment]
@maryjgoldman I would like to work on this issue. I would be grateful for some code pointers.

**Comment by acthp** [comment]
@abhishekvermasg This part of the code is very messy.

in js/views/VariableSelect.js:matchFields(), the user input is split into words, and passed to the server via matchDatasetFields. The result is stored in VariableSelect:this.state.matches. When the user clicks "DONE", the onDone() handler fires, which passes ```matches``` to this.props.onSelect, which you will find in js/containers/addWizardColumns.js as onDatasetSelect. This method also gets the list of selected datasets, and the raw text input. onDatasetSelect passes these to computeSettings, which passes them to columnSettings, which maps field match failures (nulls) to the string "[unknown]".

This is all very poorly organized, but we haven't had time to fix it. To handle match failures differently we need to either pass the parsed list of words all the way to columnSettings, or we need to use the same split algorithm on the user input in columnSettings to recover the same information. The latter is probably easier. The trim/replace/split expression in matchFields could be moved to a separate file, and required by both VariableSelect.js and addWizardColumns.js.

**Comment by abhishekvermasg** [comment]
@acthp Thank you for the code pointers. It's great help. I'll start working now.

Also, in VariableSelect.js, the following comment was there before the matchFields function:

// need to handle
// phenotypic,
// null field, null dataset
// sparse,
// dense with probemap,
// dense without probemap

Are these all issues which will create problems in future? If so, I would like to solve them all in a single go.

Also, in columnSettings in addWizardColumns.js, another comment was found:

// My god, this is a disaster.

I would like to know about that problem too. It has something to do with missing signatures, I think.

**Comment by acthp** [comment]
@abhishekvermasg The comment above matchFields was just a todo list. It should probably be deleted. I believe all of these cases are handled correctly, now, by the matchDatasetFields multimethod, above.

The comment in addWizardColumns is just a general complaint about the API for creating a column. It's not specifically about signatures. The complexity comes from the many different column types we now support: signatures, phenotype, genomic matrix (probes, genes, or probes in a gene), segmented (genes, position), and mutation (genes, position). There's also some code for composite cohorts that didn't really work out, and needs to be removed and redesigned.

So, currently, the attributes for the column are set variously in computeSettings, columnSettings, and getColSpec (the composite support). It will take some thought to figure out how to better organize it. Probably not the best place to start in the code. Also, I expect we will drop getColSpec sometime next month.
