### ISSUE TITLE
test default dataset are valid

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#188]

**Comment by jingchunzhu** [comment]
write python script for test

**Comment by abhishekvermasg** [comment]
I would like to work on this too. I would be grateful for some code pointers. @acthp

**Comment by acthp** [comment]
We load some hand-curated metadata about the public datasets when the app launches. The url is here:

https://github.com/ucscXena/ucsc-xena-client/blob/master/js/xenaQuery.js#L404

We need a python script that will verify that all of these datasets exist, to avoid errors during release. A naive way to do this would be to use the python API to fetch the dataset list for each cohort, and check that it includes the correct datasets for that cohort.

https://ucscpublic.xenahubs.net/docs/python/xena_query.py

**Comment by Abhinay1997** [comment]
@acthp I would like to work on this. Could you point me to the updated url as well as any additional context I might need ?
