### ISSUE TITLE
"I know the study I want to use" search cohort only search entire string e.g. search entire "TCGA BRCA"

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#190]
type  TCGA BRCA should find TCGA Breast invasive carcinoma (BRCA) cohort.

**Comment by maryjgoldman** [comment]
This is in the first step of the wizard to build a new visual spreadsheet

**Comment by maryjgoldman** [comment]
Will need to split input words on whitespace, and match all against the target string, in any position
