### ISSUE TITLE
Signatures don't work in Firefox

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#195]
Hi 
there seems to be a bug with Firefox using the signatures tool with Xena. I can't copy and paste stored signatures- I have to re write them with new spacing. However it works fine with chrome; you can store the signature and just paste it in
many thanks
Don

[Signatures help](https://maryjgoldman.gitbooks.io/ucsc-xena-help/content/Help_Guides/genomic-signatures.html)

**Comment by ab-anand** [comment]
![screenshot from 2018-02-20 01 04 38](https://user-images.githubusercontent.com/18382952/36394393-1c8a3b94-15da-11e8-8224-76aeeb885060.png)
Hi Mary, I've cloned the repository and I've npm installed but I'm gettting this error while doing the
 `$ npm start`

**Comment by acthp** [comment]
@ab-anand As per the error message, have to tried upgrading node? What version of node is it? Run ```node --version```

**Comment by ab-anand** [comment]
Hi, my version is 0.10.25, I've fixed this issue by installing nodejs-legacy but facing this problem now
![screenshot from 2018-02-20 11 55 26](https://user-images.githubusercontent.com/18382952/36410084-001c5630-1635-11e8-81b8-afe2ec55c8f2.png)

**Comment by ab-anand** [comment]
https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version
Following the first answer I tried to upgrade but I'm getting this error
![err](https://user-images.githubusercontent.com/18382952/36410290-1ea534d6-1636-11e8-8140-a7ab9952eedb.png)
Please help

**Comment by acthp** [comment]
@ab-anand I'm not sure why ```n stable``` would be returning an error, but you might try ```n --stable``` to see what version is available.

There are many ways to maintain node on ubuntu, so it can get a bit confusing. You'll find different directions for different strategies, and for different versions of ubuntu. For development work, I find it's best to avoid the deb packages. They're usually brittle, and out of date, and I don't like having to install dev tools as root. I install dev tools in ```~/local```, and add ```${HOME}/local/bin``` to my PATH.

You can download the tarball from https://nodejs.org, unpack it, and add the bin directory to your PATH. Like

```
wget https://nodejs.org/dist/v8.9.4/node-v8.9.4-linux-x64.tar.xz
tar Jxf node-v8.9.4-linux-x64.tar.xz
mv node-v8.9.4-linux-x64 local
```
then add ```${HOME}/local/bin``` to your path (before ```/usr/bin```, ```/usr/local/bin```, etc., where there might be other node versions).

You could also try this tool, that installs n in one step:

https://github.com/mklement0/n-install

I recommend uninstalling whatever node or n packages you currently have installed, just to avoid confusion.

**Comment by ab-anand** [comment]
Hi @acthp . Thanks 
I just moved to ubuntu 16 from 14 and installed the latest version of Nodejs. Now things are working smoothly :)

**Comment by pulkitkkr** [comment]
@maryjgoldman  Can you share the screenshot/gif recorded both on chrome and Firefox, it will be of great help. Also Please mention the step to reproduce the issue

**Comment by acthp** [comment]
Desired behavior is to be able to paste in a gene expression signature, such as "=TP53 + PTEN", for the field. User is experiencing that this fails on FF if the signature is pasted instead of typed. I'm unable to reproduce this on ubuntu, but I believe it is reproducible on OSX. I might be able to test it Friday. Example of the correct behavior:

![working](https://user-images.githubusercontent.com/494506/36572806-9393c9ac-17f2-11e8-9288-e8ae37aea95b.gif)

I believe the failing behavior is the column draws as gray, because it is not recognized as a signature. Signatures are identified as starting with '=' and successful parsing via pegjs parser. See js/parseGeneSignature.js, signature.peg, js/models/geneSignatureParser.js.

**Comment by maryjgoldman** [comment]
I'm actually not able to reproduce this any more. OSX and FF 55.0.3. I am going to email the user back and see if they are still experiencing it.

**Comment by pulkitkkr** [comment]
@maryjgoldman Tested it on Edge and Firefox (quantum) and Firefox, I'm also not able to reproduce it and already getting desired result

**Comment by pulkitkkr** [comment]
@maryjgoldman @acthp any update for this ???

**Comment by maryjgoldman** [comment]
Yes, let's close it since we can't reproduce it and I haven't heard anything back from the user
