### ISSUE TITLE
Tooltip too narrow: data getting cut off

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#20]
Example: ICGC Thyroid cancer, positional mutation, TP53. If you hover over both of the returned mutations, you can see the information is getting cut off.

**Comment by achang28** [comment]
Screenshot of issue...
![tooltipcutoff](https://cloud.githubusercontent.com/assets/3760499/13297590/ef9538ac-dae7-11e5-83e3-bb1d0594d50a.png)

**Comment by achang28** [comment]
It appears to be fixed based on the latest update to Dev:
![tooltip](https://cloud.githubusercontent.com/assets/3760499/13334510/0fe500b8-dbc1-11e5-971a-f7dfcc425c70.jpg).
Please check it out.

**Comment by jingchunzhu** [comment]
Still have the problem
![image](https://cloud.githubusercontent.com/assets/999493/13341655/82d95eec-dbef-11e5-8731-48d332d16d05.png)
