### ISSUE TITLE
Select study search field gets cleared with onBlur event

### ISSUE THREAD

**Issue by krepecka** [ucscXena/ucsc-xena-client#200]
While selecting a study in the first step of wizard with [I know the study I want to use] radio button checked [Study] field get clear if user clicks elsewhere. 
With [Help me select a study] selected search field works normally.

<img src="https://user-images.githubusercontent.com/17677991/36533010-fe36eb68-17ca-11e8-8768-b7da639f38d7.gif" width="500">

Found this while starting to work on https://github.com/ucscXena/ucsc-xena-client/issues/190.

Reproducible both on chrome (v. 63.0.3239.132) and firefox (v. 58.0). OS Ubuntu 16.04.3.

**Comment by acthp** [comment]
Thanks for the report!

**Comment by pulkitkkr** [comment]
@acthp and @krepecka  just pushed a fix for this :) 
https://github.com/ucscXena/ucsc-xena-client/pull/198
