### ISSUE TITLE
disable MuPIT in chrom view

### ISSUE THREAD

**Issue by acthp** [ucscXena/ucsc-xena-client#206]
MuPIT is only meaningful in the context of an individual gene. When viewing a chrom position, like chr17:7,500,000-7,600,000, we can have several genes in view, so sending to MuPIT is not meaningful. Current behavior is somewhat random, as MuPIT picks one of the genes in view.

We should disable the MuPIT option when in chrom view, perhaps with tooltip indicating the reason it is disabled.

**Comment by krepecka** [comment]
I would like take this on. Could you specify a bit how to display several genes in single view ? I can't seem to find how to reproduce this behavior.

**Comment by acthp** [comment]
Enter chrom region for the field.

![chrom](https://user-images.githubusercontent.com/494506/36756694-a37bb4e4-1bc4-11e8-8fe7-1ad9dc04680f.gif)
