### ISSUE TITLE
add gene labels next to gene model on chromosome view

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#210]
Currently, in chromosome view (https://xenabrowser.net/heatmap/?bookmark=897611096675ad493581415969d71d83), mouse over the gene models (in blue), tooltip will show what gene it is.  At certain zoomed-in level, when there is enough white space around the gene in the gene model diagram, show gene names on visualization. 

current:
![image](https://user-images.githubusercontent.com/999493/37006884-60e7cdb4-208f-11e8-8b65-12d53a69b1b4.png)

desired
![image](https://user-images.githubusercontent.com/999493/37006857-3ecf25ba-208f-11e8-9039-c7ab7a253212.png)

**Comment by madhavmk** [comment]
@jingchunzhu I would like to take up this issue.
Could you please direct me to which which files are related to this issue?

**Comment by ManuelLecaro** [comment]
Hello can I take up this issue @jingchunzhu ?

**Comment by jingchunzhu** [comment]
@ManuelLecaro Yes

**Comment by jingchunzhu** [comment]
fixed in https://github.com/ucscXena/ucsc-xena-client/commit/a4b8ca1ac364f90b9ad0f01bb61a58c2bd0517ff and https://github.com/ucscXena/ucsc-xena-client/commit/d3ca1273078cb752d507c3a24436b2a6a25d023a

**Comment by maryjgoldman** [comment]
Seems to be good on dev
