### ISSUE TITLE
vanishing and reappearing column menu

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#213]
The column menu will disappear when mouse move outside, and reappear when mouse moves back. The desired behavior should be the menu staying on until users click on the menu (trigger event) or click outside the menu (close menu).
 
http://g.recordit.co/0ZhCDIqztz.gif

**Comment by sanchitbansal10** [comment]
Hi, I am working on it

**Comment by shubhamshree10** [comment]
@sanchitbansal10  are you still working on it ?

I would like to ask, how to access the issue ??
I don't know exactly what the problem is.

**Comment by maryjgoldman** [comment]
@shubhamshree10 The problem is that the column menu disappears and then reappears. We want the menu to be visible even if they mouse away from the column.

**Comment by sanchitbansal10** [comment]
@maryjgoldman @acthp 
plaease review the PR#238

**Comment by sanchitbansal10** [comment]
@jingchunzhu please review the PR#238...The issue is fixed

**Comment by jingchunzhu** [comment]
Thank you @sanchitbansal10 !  I just merged your PR.
