### ISSUE TITLE
Problem with setting up the Codebase

### ISSUE THREAD

**Issue by hitesh4** [ucscXena/ucsc-xena-client#215]
I am facing a problem with setting up the codebase on my local machine. I think it's probably due to the versions of NPM and NodeJS (Not Sure).

The terminal errors I am getting are-

npm http 200 http://registry.npmjs.org/yauzl/-/yauzl-2.8.0.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hitesh/GSOC/ucsc-xena-client/npm-debug.log
npm ERR! not ok code 0

Whereas the npm-debug.log file says-
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install' ]
2 info using npm@1.3.10
3 info using node@v0.10.25
.
.
.
784 info preuninstall cypress@2.1.0
785 info uninstall cypress@2.1.0
786 verbose true,/home/hitesh/GSOC/ucsc-xena-client/node_modules,/home/hitesh/GSOC/ucsc-xena-client/node_modules unbuild cypress@2.1.0
787 verbose /home/hitesh/GSOC/ucsc-xena-client/node_modules/.bin,[object Object] binRoot
788 info postuninstall cypress@2.1.0
789 error 404 'cypress' is not in the npm registry.
789 error 404 You should bug the author to publish it
789 error 404
789 error 404 Note that you can also install from a
789 error 404 tarball, folder, or http url, or git url.
790 error System Linux 4.4.0-109-generic
791 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
792 error cwd /home/hitesh/GSOC/ucsc-xena-client
793 error node -v v0.10.25
794 error npm -v 1.3.10
795 error code E404
796 verbose exit [ 1, true ]

Can you please help me out resolving this issue?

**Comment by acthp** [comment]
These versions of node & npm are extremely out of date. Latest node version is 8.9, but even versions as old as 4.0 should work. Version 0.10 is not going to work.

**Comment by hitesh4** [comment]
Thanks for the support I was able to set it up successfully.
