### ISSUE TITLE
Hitting return during a search of phenotypes makes it impossible to select a phenotype from the auto-suggest

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#222]
To reproduce:
1. type a few letters into the phenotype search (see gif)
2. hit return
3. see that the auto-suggest goes away
4. click out of the phenotype search bar and back in the phenotype search bar
5. see that the auto-suggest returns
6. attempt to click on item in auto suggest but you can't select anything.

![returnerror](https://user-images.githubusercontent.com/13877333/37314844-9427a846-2613-11e8-89ee-508f342b7661.gif)

**Comment by syt123450** [comment]
Could give out some environment paramenter? I try it in my mac, chrome environment, it seems that this function can work well. When I click the auto suggest, it will be added to "Phenotype" part. @maryjgoldman

**Comment by maryjgoldman** [comment]
@syt123450 Interesting, I'm able to reproduce it consistently. I am on chrome Version 64.0.3282.186. OSx 10.11.6. @acthp Are you able to reproduce this?

**Comment by sanchitbansal10** [comment]
@maryjgoldman i am able to reproduce this....Chrome 64 and ubuntu 16.04

**Comment by sanchitbansal10** [comment]
@maryjgoldman opened a PR #226

**Comment by shubhamshree10** [comment]
@maryjgoldman   
I ran in my localhost with no problems in selecting.
The error you have mentioned is either not there or it is fixed, please do **close this issue**

**Comment by sanchitbansal10** [comment]
@shubhamshree10 its fixed and PR is merged
