### ISSUE TITLE
Gray out filter menu options if no samples match the search

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#223]
Still allow users to click on the menu so that they can see what the options might be *if* a sample matched their search term, but gray out the words 'filter' 'clear filter' 'zoom' and 'new column'

![grayoutfilter](https://user-images.githubusercontent.com/13877333/37316224-2410c594-261b-11e8-9e22-e30b52337148.gif)

**Comment by superdyzio** [comment]
I'll fix that!

**Comment by superdyzio** [comment]
PR opened @maryjgoldman

**Comment by superdyzio** [comment]
@maryjgoldman @acthp 
Actually, `Clear Filter` shouldn't be active always when any filter was applied?
Also, seems that `Reload Cohort Data` button does not work but filters can be removed by clicking on `Filtered to` label on the left.

**Comment by superdyzio** [comment]
Looks like this is fixed now on master, I'm closing my forgotten PR.
