### ISSUE TITLE
Toggle button don't show up when there is only one column

### ISSUE THREAD

**Issue by sanchitbansal10** [ucscXena/ucsc-xena-client#229]
Environment: Firefox dev edition, Ubuntu

![ucsc-issue](https://user-images.githubusercontent.com/16536741/37552074-b9ce2e9e-29d3-11e8-87e2-cfdff40bfdf9.gif)

**Comment by sanchitbansal10** [comment]
@acthp is his issue valid? i'll work on this then

**Comment by jingchunzhu** [comment]
this is not a bug fix issue. it's a ux design issue. @sanchitbansal10, we will give this to our UX designer. Thanks. You dont need to address this.

**Comment by sanchitbansal10** [comment]
@jingchunzhu thanks..I am interested in applying for GSOC 2018. The project i would like to work on is BRCAness view. I have initiated a conversation on google group, till now reply have came....

Can u pls look into it i need to get some info to workout the proposal.
Thanks
