### ISSUE TITLE
Setup Zenhub for Xena Team

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#248]
- [ ] User Permissions
- [ ] Columns to match process
- [ ] Invite UCSC team

**Comment by NoopDog** [comment]
Mary, this is ready for your review on CC-Stage.. hah not really!

**Comment by NoopDog** [comment]
@jingchunzhu can you go into zenhub and login with your github credentials and then invite everyone to the team? (me, Fran, Mim, Brian, Mary etc.)  I can get on a screen share with you in your afternoon to try to get through this.

I dont seem to be able to assign tickets, or create milestones maybe the above will fix.

**Comment by jingchunzhu** [comment]
I am stuck at invite.   The Invite button at the bottom does not become active.

![image](https://user-images.githubusercontent.com/999493/42777784-e3a7abac-88ef-11e8-9817-3b9a0a420e1e.png)

**Comment by NoopDog** [comment]
<img width="450" alt="screen shot 2018-07-17 at 10 10 53 am" src="https://user-images.githubusercontent.com/3239697/42789631-b4df1e58-89a9-11e8-8bdb-428bd6bb2d87.png">

I think you need to type in my email `dave@clevercanary.com` where is says add this team members email...

Let me know if that fixes it.

**Comment by jingchunzhu** [comment]
sent out five invitations (Dave, Fran, Mim, Brian, Mary)
