### ISSUE TITLE
Align Scatter Plot Controls

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#257]

**Comment by NoopDog** [comment]
Lets add a book mark and the screen shot..

**Comment by maryjgoldman** [comment]
http://dev.xenabrowser.net/?bookmark=46677826795a217b2a38bdeccbaef939
![alignscatterplot](https://user-images.githubusercontent.com/13877333/42662315-06c4c97e-85e6-11e8-9024-652ed08f53ee.png)

**Comment by NoopDog** [comment]
@maryjgoldman this is on stage for your review.
http://cc.xenabrowser.net/?bookmark=46677826795a217b2a38bdeccbaef939
