### ISSUE TITLE
Fix Stats Vertical Overflow on Many Genes or Probes

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#258]

**Comment by maryjgoldman** [comment]
http://dev.xenabrowser.net/?bookmark=c8e20f1e942f465457aa6b7f2ca80874

**Comment by maryjgoldman** [comment]
![statsoverflow](https://user-images.githubusercontent.com/13877333/42662520-be70b8ee-85e6-11e8-80c1-7be69a1d066d.png)

**Comment by maryjgoldman** [comment]
Happens when the y axis of many genes or probes, x axis a categorical column

**Comment by NoopDog** [comment]
Hi @frano-m lets review and see if we can come up with something other than the scroll bar approach.

**Comment by NoopDog** [comment]
@maryjgoldman this is ready to review on cc.xenabrowser.net

**Comment by maryjgoldman** [comment]
This is good enough to push. I will make a new issue to ask to remove the comma between the p value and f statistic. I know it's small thing but both Jing and I noticed and didn't like it.

Attempt at high level explanation of why we both want no comma: The p value is further calculation based on the f statistic and some other information. The comma makes it seem like the f statistic is in addition to the p value, when really they are two numbers documenting the same thing.
