### ISSUE TITLE
Update Legend for Mutation Columns

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#259]
1. Group types of the same color.
1. Modify for boxes and text legend.

**Comment by maryjgoldman** [comment]
After: https://docs.google.com/presentation/d/1eJ-hwlYI3EgB34iSM8fdp2MFeEtSLoS0XPnJ-d-lzc4/edit#slide=id.g3541a2a88e_0_173 --> slide 2
![mutations2](https://user-images.githubusercontent.com/13877333/42663075-e42ecd3a-85e8-11e8-959f-bc5cc73cdae5.png)

**Comment by maryjgoldman** [comment]
Note, only show each of the mutation types in the legend if they are present in the plot. Each plot will vary by gene

**Comment by jingchunzhu** [comment]
Mary, do we have to "only show each of the mutation types in the legend if they are present in the plot. Each plot will vary by gene". How about just showing the same legend for every mutation column.

**Comment by maryjgoldman** [comment]
That could work. I just figured we were already only showing what is there so the code must already be in place. So hook up the new legend to the same code.

**Comment by jingchunzhu** [comment]
I vote for the easier one , same legend across all mutation columns.

**Comment by maryjgoldman** [comment]
At first I wanted the other one but after thinking about it more, you're right. It's easier, the old version doesn't add much, and if they want to use the legend in a real figure they'll probably need to edit it anyways so editing out colors that aren't there isn't too much more work. 

And on the off chance their first plot has all blue mutations or something like that, they will realize that we don't just color all mutations blue. That the color means something and if they open another plot they'll see that.

**Comment by jingchunzhu** [comment]
https://github.com/ucscXena/ucsc-xena-client/commit/34babd88af12b8f42badbcaadbe1447129716e58

**Comment by maryjgoldman** [comment]
Looking good! It seems to me like the words 'Variant Impact' and the 'no data' bar should be inside the card outline. Is this possible?

**Comment by jingchunzhu** [comment]
on beta
