### ISSUE TITLE
Update Genomic Assay Type Selector to Show Assembly Number

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#265]
http://localhost:8080/?bookmark=9a34aa99d81149170ad0145c3be2d9e3
Edit Column C

Or on dev
http://dev.xenabrowser.net/?bookmark=9a34aa99d81149170ad0145c3be2d9e3

grep for `badge` to find the codez.

**Comment by NoopDog** [comment]
@maryjgoldman this is on http://cc.xenabrowser.net/?bookmark=9a34aa99d81149170ad0145c3be2d9e3 for your review.

Lets discuss if something else needs to be done for your demo.

**Comment by maryjgoldman** [comment]
The text needs to be darker just for readability but otherwise this looks good. @jingchunzhu this looks ok to you as well?

**Comment by acthp** [comment]
Something went off with the css for the error message to the user.

![image](https://user-images.githubusercontent.com/494506/42897175-06b34a0e-8a74-11e8-8ef8-d7984c4cbe72.png)

Independently, we've found a bug in my code for triggering the error message, so it isn't displayed in all cases that it should be. You can get the error message display by typing "chr1" as the field, and selecting the two methylation tracks in TCGA BRCA.

**Comment by acthp** [comment]
here's what it looks like on master

![image](https://user-images.githubusercontent.com/494506/42897333-92901bf6-8a74-11e8-9609-c2406f1a15f7.png)

**Comment by NoopDog** [comment]
From BC

> Just chatted with Mary & have a couple more ideas about displaying assembly.
First, the current code is too restrictive, in that it disallows positions "chr12" and "chr12p" on different assemblies. We can actually map those to different assemblies. The restriction should only be when there are coordinates. I'll update the rule to handle this correctly.
Second, we're hesitant to put the assembly in the "basic" mode, because it will be confusing to "basic" users. We thought maybe the assemblies for the datasets should fade in when the user types a position with coordinates. We could do the same thing in "advanced" mode, to be consistent.
