### ISSUE TITLE
CSS woes when zooming in transcript view

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#277]
When zooming on a transcript in transcript view, the top and bottom of the graph is truncated and the graph is not aligned to the middle.

How it is supposed to look:

![Figure 4 (2).png](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/c37a505a-566f-43f5-9fc7-1889615741c2)

(ignore the legend bit)

How it looks now:

![badTranscriptView.png](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/94b64bd5-cd9a-48b8-98ed-33f4bef41ddb)

http://xenabrowser.net/transcripts/?bookmark=80d9c57b471b654cc569d4ceb44e6591

To trigger: go to transcript view (http://dev.xenabrowser.net/transcripts/), enter a gene and select any two groups. Click on one of the rows to zoom.

**Comment by jingchunzhu** [comment]
fixed commit https://github.com/ucscXena/ucsc-xena-client/commit/f274994d8202272954e1bc299c317a478e915d4a
