### ISSUE TITLE
Hover Instructions on Zoom

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#324]

**Comment by NoopDog** [comment]
@maryjgoldman we have deployed some changes to the wording of the instructions once you click and hold, and also once you drag.  We basically removed the words "horizontal" / "vertical" or  "sample" "annotation" and just say Zoomed to rows 1-10 or "drag to zoom" or Zoomed to 7pct.

Its obvious which direction you are moving so hopefully this is enough information to guide the user. Try it out and let us know how it feels. 

Thanks,
D

**Comment by maryjgoldman** [comment]
I like it. Shorter is better.

I think my only comment is that it should be 'zoom' rather than 'zoomed'. Zoomed is past tense and makes it sound like we already zoomed, when really what we going to do (future) is zoom to the area under selection.

**Comment by maryjgoldman** [comment]
Is this the right github issue to ask that the hover text for the zoom in the header be 'click and drag to zoom' ? I think it's a better to start with the action rather than 'zoom - click and drag' since you can already see in the header that it is about zoom. Open to other ideas here

**Comment by NoopDog** [comment]
Hi @maryjgoldman "click and drag" and "Zoom to" are deployed to cc-staging
Cheers,
D

**Comment by maryjgoldman** [comment]
Both the hover and the text while zooming looks great. Thanks!
