### ISSUE TITLE
Clear Sample Zoom

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#327]

**Comment by NoopDog** [comment]
@maryjgoldman we will try making the sample zoom cancel in the samples column and also maybe try to make the cancel in the status bar header more visible.  Stay tune.

**Comment by maryjgoldman** [comment]
+1 Sounds good

**Comment by NoopDog** [comment]
@jingchunzhu are you ok with how the clear sample zoom is working? If so lets close this. We can revisit if we have issues.
