### ISSUE TITLE
Zooming to less than one sample results in gray visual spreadsheet

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#351]
If you zoom in vertically to one sample and then try to zoom again the spreadsheet goes blank and the sample range is something like 92-91. 

Example of resulting state: http://cc.xenabrowser.net/heatmap/?bookmark=686ba4e06d50c7c58151b0ea4f44c0bb

We want to mirror the functionality we have on production where if you zoom in to less than one sample you still always show at least one sample.

**Comment by NoopDog** [comment]
Hi @maryjgoldman is this looking ok now? The fix should be on cc-staging.

**Comment by maryjgoldman** [comment]
Looks good!

**Comment by maryjgoldman** [comment]
@NoopDog

**Comment by NoopDog** [comment]
thx @maryjgoldman closing!
