### ISSUE TITLE
Website Updates - Feb 28 Deadline

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#355]

**Comment by NoopDog** [comment]
Hi @jingchunzhu let us know if there are any show stoppers or if Brian can proceed with the DNS switch and https cert install.

**Comment by jingchunzhu** [comment]
I see one right now. The right section has one more line of text than the left side in the screenshot, causing the buttons not line up.  Can you change the right side text to “View your data, securely and privately. Our step-by-step wizard will guide you.”  Essentially deleting the last bits, so it will be two lines and the two sides line up perfectly.   Don’t see  any other show stoppers.

![image](https://user-images.githubusercontent.com/999493/53621117-4afbb600-3baa-11e9-8f18-9a1db51213ff.png)
