### ISSUE TITLE
Missing horizontal zoom out UI for some of the columns

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#361]
The first issue is the missing horizontal zoom out UI for some of the columns, such as example a column D, E, and F, they all seem to be the matrix type column with multiple subcolumns.

**Comment by NoopDog** [comment]
a) http://cc.xenabrowser.net/?bookmark=aaf9131476a877fe1d7e0a34c4d2fc84
b) http://cc.xenabrowser.net/?bookmark=e73d308ea8ba6eec218a9b242a8e7b59
c) http://cc.xenabrowser.net/?bookmark=fbc32ba42b2ddc4d2bd76b524c3e5b4b
d) http://cc.xenabrowser.net/?bookmark=92df6224911a5d7ce3c98b8302533460 

Hi @jingchunzhu the fix for this is on http://cc.xenabrowser.net for your review.

**Comment by NoopDog** [comment]
Hi @jingchunzhu can you let us know if this is still an issue?  I think it should be fixed.

**Comment by jingchunzhu** [comment]
Resolved. Not an issue anymore.
