### ISSUE TITLE
The tooltip for “example a column E”, the tooltip is huge and reports all the samples values, it should report just for the sample that is under the mouse. 

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#362]

**Comment by NoopDog** [comment]
The second issue is the tooltip for “example a column E”, the tooltip is huge and reports all the samples values, it should report just for the sample that is under the mouse

**Comment by NoopDog** [comment]
@jingchunzhu This should be fixed as well.

**Comment by jingchunzhu** [comment]
Looks good.
