### ISSUE TITLE
feature vanishes after a few seconds in wizard edit mode

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#366]
See the following .gif movie, you can see the feature DFI is initially listed in the wizard edit window, after a few seconds, it is gone.

![vanishingfeatureinwizard](https://user-images.githubusercontent.com/999493/52452585-73871780-2af8-11e9-95d9-cc0f49f3dd64.gif)

to reproduce, start with https://xenabrowser.net/heatmap/?bookmark=76c540eee254666c44042805666d5832, click on hamburger icon on column C.

**Comment by Vivekrajput20** [comment]
I would like to work on the issue.

**Comment by jingchunzhu** [comment]
go ahead

**Comment by geka412315** [comment]
> I would like to work on the issue.
How is the work on this going? :)

**Comment by Nicholaz99** [comment]
@jingchunzhu Hi, my name is Nicholas and I would like to try to fix this bug. May I know what is the known behaviour of the bug? Does the checkbox should have disappeared from the beginning or should not disappear at all? Thank you so much.

**Comment by jingchunzhu** [comment]
fixed https://github.com/ucscXena/ucsc-xena-client/commit/ba200b341490eedecb1a861bf75cd9ca1365de0c

**Comment by maryjgoldman** [comment]
This looks good on dev. Will keep open to test on beta and production
