### ISSUE TITLE
use information in configuration file to generate Tumor Map linkout

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#367]
currently, the mapping between xena cohort to tumor map is hard-coded in the xena client code at https://github.com/ucscXena/ucsc-xena-client/blob/master/js/views/Column.js#L258

use the configuration file here to generate the linkout
https://github.com/ucscXena/cohortMetaData/blob/master/defaultTumormap.json

**Comment by ganeshpatro321** [comment]
Hello @jingchunzhu , I would like to work on this issue, please assign me if work for the same has not been done.

**Comment by jingchunzhu** [comment]
Go for it

**Comment by ganeshpatro321** [comment]
hello @jingchunzhu I wanted to know if there are any API, or scripts which provide the JSON data

**Comment by ganeshpatro321** [comment]
@jingchunzhu 
Do you want me to link out the repository directly or create JSON file in the client repository?

**Comment by jingchunzhu** [comment]
The location of the metadata directory is already in the client code:
 https://github.com/ucscXena/ucsc-xena-client/blob/master/js/cohortMetaData.js#L2

The "raw" url for the tumor map mapping file is inside that directory, please use the raw url location https://raw.githubusercontent.com/ucscXena/cohortMetaData/master/defaultTumormap.json

Check out examples of how client gets similar information about other metadata,
https://github.com/ucscXena/ucsc-xena-client/blob/master/js/xenaQuery.js#L430
https://github.com/ucscXena/ucsc-xena-client/blob/master/js/xenaQuery.js#L466

**Comment by jingchunzhu** [comment]
implemented in d5387b5a6aae857973c62b11ed10035ff6b5301a
