### ISSUE TITLE
Remove or hide zoom status in chart view

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#370]
http://cc.xenabrowser.net/?bookmark=efd3361a03d1792f5fb12cbefac51c0c .

On the above chart view the zoom bar text and controls need to be hidden.

![Screen Shot 2019-02-21 at 11.48.30 AM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/4769a061-ec36-4e3f-a04b-00114d00d9b2)

**Comment by NoopDog** [comment]
Hi @jingchunzhu this should be fixed on http://cc.xenabrowser.net/?bookmark=efd3361a03d1792f5fb12cbefac51c0c

Cheers,
Dave

**Comment by jingchunzhu** [comment]
looks great!
