### ISSUE TITLE
Viz settings: can't turn off normalization

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#38]
turning it off doesn't do anything

**Comment by achang28** [comment]
Please assign to me.

**Comment by jingchunzhu** [comment]
It is not that important to have the custom setting to work as in old code -- the auto setting seems fine and no one complaint.

It is more important to have the normalization be turned off.

**Comment by achang28** [comment]
For the normalization drop-down menu, should the values be of type boolean or string?

![normalize - boolean](https://cloud.githubusercontent.com/assets/3760499/13684771/0fb27f2e-e6c2-11e5-8738-e9384656de64.png)

![normalize - named](https://cloud.githubusercontent.com/assets/3760499/13684826/57b64738-e6c2-11e5-8514-4489cecf5c88.png)

**Comment by jingchunzhu** [comment]
These are the options under the CHART viewing mode.  Should be "none" and one of the others (either "across cohort" or "across selected samples")  --- I am not sure which one it is on top of my head.

![image](https://cloud.githubusercontent.com/assets/999493/13685322/b90d2c84-e6c4-11e5-8e17-a12560031f82.png)

**Comment by achang28** [comment]
@jingchunzhu If I remember correctly, you had mentioned to only normalize across the chosen samples when this setting was chosen?

**Comment by jingchunzhu** [comment]
It is "across selected samples" in the "heatmap" mode

in chart.js, here are the settings.  --- note these are not the same state key/parameter (whatever you call it).  In chart, the normalization is only applied to the single column. In heatmap, it is applied to the whole dataset.  So these are two different parts in the state object (if they are referred to the same state objects, i don't know).   But i think the wording and values should be the same.  

dropDown = [{
						"value": "none",
						"text": "none",
						"index": 0
					}, //no normalization
					{
						"value": "cohort",
						"text": "across cohort",
						"index": 1
					}, //cohort-level
					{
						"value": "subset",
						"text": "across selected samples",
						"index": 2
					} //selected sample level current heatmap normalization

**Comment by jingchunzhu** [comment]
how about just have "none" and "across selected samples" ?

**Comment by acthp** [comment]
closed via a26d323936d43aa01f105a8c719ac328a69749fb
