### ISSUE TITLE
can't zoom on bottom samples

### ISSUE THREAD

**Issue by acthp** [ucscXena/ucsc-xena-client#395]
Dragging over the bottom samples in a column does not capture the last samples in the column. E.g. in tcga brca, with 1247 samples, trying to zoom on the bottom will result in a zoom up to sample 1245. Samples 1246 and 1247 are inaccessible.

Probably due to samplesZoom using floor for both the start and end projections. End zoom should be the last index under the pixel, rather than the first.

**Comment by frano-m** [comment]
@NoopDog @MillenniumFalconMechanic can we investigate `send` in the file `columnZoom.js` (function samplesZoom).

If a column has a height of say 436px, and the cross hair is at the bottom most part of the column, then `send` is calculated as 435px (not 436px).

This may have something to do with the zoom on bottom samples problem.  It is only borked when there is a large number of samples and so perhaps the 1px difference is enough to blow out the row calculations. 

I wonder if our nifty capping of the zoom tooltip at the bounds of the column has anything to do with this?

**Comment by NoopDog** [comment]
@acthp a fix for this is on cc-staging http://cc.xenabrowser.net/

Will PR in a bit for you to review.

Cheers,
D

**Comment by jingchunzhu** [comment]
looks  good on cc.xenabrowser.net

**Comment by maryjgoldman** [comment]
agree: looks good on cc.xenabrowser.net

@acthp if you want to review the code and then mark this as done, I think we'll be set.

**Comment by NoopDog** [comment]
OK this fix was not working properly. We have since updated the code and this is ready to test again. Thanks @maryjgoldman @jingchunzhu

**Comment by maryjgoldman** [comment]
I tested this as part of my testing for #418 and it looks good
