### ISSUE TITLE
Change text references for Assay Type to Data Set

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#403]
The instructions here use "Data Set" and "Assay Type" to mention the same thing.
Lets standardize on "Data Set".

Lets also find out where else this might be used in the app.

![Screen Shot 2019-03-13 at 12.33.14 PM.png](https://images.zenhubusercontent.com/57323611bf93871ccd9ad094/0c311894-68a0-41dc-ac5e-7cd64717b718)

**Comment by NoopDog** [comment]
@frano-m can you take a look at this one? Thanks!

**Comment by NoopDog** [comment]
Hi @maryjgoldman this is on CC staging for your review. Thanks!

**Comment by maryjgoldman** [comment]
Poked around to see if I could find any other instances of 'assay type' and it appears to all be 'dataset'. Looks good.

**Comment by NoopDog** [comment]
Thx Mary

------------------------------
Dave Rogers
Partner, Clever Canary
646-286-5371
http://clevercanary.com

@CleverCanary
@_DaveRogers
https://www.linkedin.com/pub/dave-rogers/0/90/92


On Jun 11, 2019, at 4:08 PM, maryjgoldman <notifications@github.com> wrote:

Poked around to see if I could find any other instances of 'assay type' and
it appears to all be 'dataset'. Looks good.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ucscXena/ucsc-xena-client/issues/403?email_source=notifications&email_token=AAYW6EP5TCXNK453GYLYSHDP2AV5PA5CNFSM4G6AGCH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXOYITI#issuecomment-501056589>,
or mute the thread
