### ISSUE TITLE
Twitter feed on front page not updating

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#417]
On the front page it has the tweet from Feb 7: ![Screen Shot 2019-04-15 at 11.24.12 AM.png](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/c452a010-5200-4957-8f5e-b54b80b9e2b3)

But our latest tweet is actually: https://twitter.com/UCSCXena/status/1112394126052478978

**Comment by NoopDog** [comment]
HI @frano-m I think we can pick this back up now. Thanks!

**Comment by frano-m** [comment]
Original placeholder tweet has been removed and replaced with live embedded Tweets

**Comment by NoopDog** [comment]
@maryjgoldman @jingchunzhu  this is on stage for your review.  https://staging.xena.ucsc.edu/

**Comment by maryjgoldman** [comment]
It has our most current twitter link which is great! But the formatting looks a bit off. On our current homepage the bookmark link is bigger and the image is off to the right. On staging the link is smaller and the image is under the text.

Really this is about the 'What's new' space looking nicer. I'm not that concerned that the link is small, etc. Just that most of the 'What's new' space is empty, making it look like we don't have much new content when really we do.

**Comment by NoopDog** [comment]
Hi @maryjgoldman yes the look of the actual embedded tweet is controlled by twitter to keep it looking like a tweet. But yes it does look a bit bare. We could do the latest 3 tweets horizontally (i think) and switch them to vertical on narrower browsers. Shall we give that a go?

Cheers,
D

**Comment by maryjgoldman** [comment]
Assuming it's not a lot of work, that would be great!

**Comment by jingchunzhu** [comment]
Love it to have the latest tweet.

**Comment by maryjgoldman** [comment]
@jingchunzhu do you mean ONLY have the latest tweet? Or for the latest tweet to be the left-hand tweet in the row of 3 tweets?

**Comment by jingchunzhu** [comment]
I just meant to have actual tweet show up automatically, not mock up,  is awesome.

**Comment by NoopDog** [comment]
Yes, the tweets are live on staging. (pulls the latest real tweet) I think its easy to pull the last 3. Will check with  @frano-m when she comes online.  Thanks!

**Comment by NoopDog** [comment]
So yes, we can get more than one tweet, but its not straightforward to control the layout. Twitter wants to control how the tweets look ( so they look like tweets which is probably a good idea).

What we can try is to just keep the first 3 tweets on the left and  then move the "subscribe" box to the right of the tweet list.  We will put that on stage in a bit to see what you think.  @maryjgoldman @frano-m @jingchunzhu

**Comment by maryjgoldman** [comment]
Thanks for giving this a try! I think I prefer the way it was before with the single tweet and then the newsletter below. With this it feels like the newsletter gets lost. 

I'm fine with pushing out the previous version (1 tweet, newsletter below) as is. @jingchunzhu do you agree?

**Comment by maryjgoldman** [comment]
Or @jingchunzhu I could also be convinced the new version doesn't lose the newsletter too much. Whichever you prefer.

**Comment by jingchunzhu** [comment]
Both versions are great and beautiful to me.   If I have to choose one, the 3x tweet version.

**Comment by NoopDog** [comment]
OK thanks for the feedback. So are we ok with how it is now then? I feel the the "subscribe" is still visible but balances off the blank area.

I do feel the 3 tweet versions makes it clear there is some history.

**Comment by maryjgoldman** [comment]
Yep, good as is. Let's push it out!
