### ISSUE TITLE
Intermittent zoom bug where last sample is +1 total samples

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#418]
If you zoom a large % of the samples and all the way to the last sample sometimes the zoom says there are one more than the total number of samples in view. Example below: 10518 samples but zoomed to 6079 - 10519 (i.e. one more than how many samples are in view).
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3562333466343261383963316663316666653863653961362f33373161613330352d316462392d343766302d616164362d306135396239363965373634](https://user-images.githubusercontent.com/13877333/56250816-c7b4f780-6065-11e9-8337-cad6e61ddc10.png)

Examples: http://cc.xenabrowser.net/heatmap/?bookmark=5d059a700cbf8b9f7d3080013bdc0790 http://cc.xenabrowser.net/heatmap/?bookmark=bdf4fb9e1659d981881513ae84519461 http://cc.xenabrowser.net/heatmap/?bookmark=8333fcf4b70993ddc8dd7a58772f520c http://cc.xenabrowser.net/heatmap/?bookmark=ac2386da0dba7ffc58357799982cab15

Unfortunately is not reliably reproducible (maybe 1 out 6 times) Seems to happen the most frequently with:
a) fresh tab (try starting here: http://cc.xenabrowser.net/heatmap/?bookmark=bc7f3f46b042bcf5c099439c2816ff01)
b) not the first time you zoom in to a large % of the samples and all the way to the last sample, but the second, third or fourth
c) not sure if this is my imagination or not, but seems to happen more reliably if the help bubbles are still in view (i.e. don't close them). E.g. 
![Screen Shot 2019-04-16 at 4 40 04 PM](https://user-images.githubusercontent.com/13877333/56250944-604b7780-6066-11e9-8ae0-db28723f01f7.png)

**Comment by NoopDog** [comment]
Thanks @maryjgoldman and thanks for detailed steps to reproduce.

**Comment by NoopDog** [comment]
@maryjgoldman there is a fix on http://cc.xenabrowser.net/ that should address this. Can you retest please? Thanks, D

**Comment by maryjgoldman** [comment]
Well it was intermittent to begin with, but as far as I can tell, this is fixed. Tested on 12 new tabs.
