### ISSUE TITLE
mean/median tooltip is wrong after horizontal zoom

### ISSUE THREAD

**Issue by acthp** [ucscXena/ucsc-xena-client#424]
Load a geneset. Note mean/median on 1st and 2nd column. Zoom on 2nd column. Tooltip will show mean/median of the 1st column.

Happens because when we slice the heatmap data, we don't slice the mean/median data.

**Comment by jingchunzhu** [comment]
this seems to be already fixed on production

**Comment by maryjgoldman** [comment]
I confirm. Seems to be fixed on production. Also is not broken if you cluster.
