### ISSUE TITLE
Tooltip reports mean and median for null values in categorical phenotype fields

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#443]
Even though the mean and median is blank, should not even be in there since it is a categorical feature rather than a numeric feature.

**Comment by jingchunzhu** [comment]
This seems to have been fixed on production

**Comment by maryjgoldman** [comment]
It still seems broken to me?

https://xenabrowser.net/heatmap/?bookmark=41b43977fb3e1dea3176b6a5c90030e1

![Screen Shot 2019-08-29 at 3 18 51 PM](https://user-images.githubusercontent.com/13877333/63980434-7afc1700-ca70-11e9-96d3-12403c293221.png)

**Comment by jingchunzhu** [comment]
sorry. did not see the word "blank" in your description.

**Comment by jingchunzhu** [comment]
fixed in 377b5634046ccc09a4f1bc06b52b4997ff08a744
