### ISSUE TITLE
link in local xena hub is broken

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#457]
The button here:
![Screen Shot 2019-12-07 at 5 04 52 PM](https://user-images.githubusercontent.com/13877333/70371900-bb8eea80-1913-11ea-8a00-a2174785e066.png)
goes to https://xenabrowser.net/datapages/?host=https%3A%2F%2Flocal.xena.ucsc.edu%3A7223. This does not load the page correctly. It needs to instead go to https://xenabrowser.net/datapages/?addHub=http%3A%2F%2F127.0.0.1%3A7222&host=http%3A%2F%2F127.0.0.1%3A7222

**Comment by aashimgarg** [comment]
What is the preknowledge that i need to have to solve these issues?

**Comment by jingchunzhu** [comment]
fixed in https://github.com/ucscXena/ucsc-xena-client/commit/1cfa37e812f1d84263b3f3d13add181ac653c344
