### ISSUE TITLE
No bottom to top button in this following "project/tutorials" page

### ISSUE THREAD

**Issue by aashimgarg** [ucscXena/ucsc-xena-client#458]
As this following page contains long written amount of text. So i think i can add a bootom to top button in this following page and make its position sticky for the user to get directly to the top of the page.

**Comment by maryjgoldman** [comment]
Are you talking about a javascript element that follows the user as they scroll that allows them to go to the top of the page? If this is the case then we don't have control over this since the help pages are rendered via Gitbook. Please feel free to contact Gitbook about this.
