### ISSUE TITLE
deep linking broken within Xena . . Error: keys should be an array

### ISSUE THREAD

**Issue by nathandunn** [ucscXena/ucsc-xena-client#474]
I noticed from the Xena GeneSet Viewer that the links are broken: 
https://github.com/ucscXena/XenaGoWidget/issues/701

Also, most of the examples links (4 and on) from the documentation are also broken:

https://ucsc-xena.gitbook.io/project/technical-documentation/deep-linking-into-xena

![image](https://user-images.githubusercontent.com/751274/108066889-d8917400-7014-11eb-84e5-29b38fa8b3cb.png)

Sample links from the Xena GeneSet Viewer:

https://xenabrowser.net/heatmap/?columns=%5B%7B%22name%22%3A%22pathway_act%2FTCGA_PRAD_BPA_Z.tsv%22%2C%22host%22%3A%22https%3A%2F%2Fxenago.xenahubs.net%22%2C%22fields%22%3A%22EHMT2_tf_targets%22%2C%22columnLabel%22%3A%22Gene%20Expression%20Activity%22%2C%22fieldLabel%22%3A%22EHMT2_tf_targets%22%7D%2C%7B%22name%22%3A%22tpm_z%2FTCGA_Prostate_Cancer__PRAD_.z.tpm%22%2C%22host%22%3A%22https%3A%2F%2Fxenago.xenahubs.net%22%2C%22fields%22%3A%22USF1%2CKLK3%22%2C%22columnLabel%22%3A%22Gene%20View%22%2C%22fieldLabel%22%3A%222%20genes%20%22%7D%5D&heatmap=%7B%22showWelcome%22:false%7D

https://xenabrowser.net/heatmap/?columns=%5B%7B%22name%22%3A%22pathway_act%2FTCGA_PRAD_BPA_Z.tsv%22%2C%22host%22%3A%22https%3A%2F%2Fxenago.xenahubs.net%22%2C%22fields%22%3A%22EHMT2_tf_targets%22%2C%22columnLabel%22%3A%22Gene%20Expression%20Activity%22%2C%22fieldLabel%22%3A%22EHMT2_tf_targets%22%7D%2C%7B%22name%22%3A%22pathway_act%2FTCGA_PRAD_BPA_Z.tsv%22%2C%22host%22%3A%22https%3A%2F%2Fxenago.xenahubs.net%22%2C%22fields%22%3A%22LATS2_tf_targets%22%2C%22columnLabel%22%3A%22Gene%20Expression%20Activity%22%2C%22fieldLabel%22%3A%22LATS2_tf_targets%22%7D%2C%7B%22name%22%3A%22pathway_act%2FTCGA_PRAD_BPA_Z.tsv%22%2C%22host%22%3A%22https%3A%2F%2Fxenago.xenahubs.net%22%2C%22fields%22%3A%22PA2G4_tf_targets%22%2C%22columnLabel%22%3A%22Gene%20Expression%20Activity%22%2C%22fieldLabel%22%3A%22PA2G4_tf_targets%22%7D%2C%7B%22name%22%3A%22pathway_act%2FTCGA_PRAD_BPA_Z.tsv%22%2C%22host%22%3A%22https%3A%2F%2Fxenago.xenahubs.net%22%2C%22fields%22%3A%22HIP1_tf_targets%22%2C%22columnLabel%22%3A%22Gene%20Expression%20Activity%22%2C%22fieldLabel%22%3A%22HIP1_tf_targets%22%7D%2C%7B%22name%22%3A%22pathway_act%2FTCGA_PRAD_BPA_Z.tsv%22%2C%22host%22%3A%22https%3A%2F%2Fxenago.xenahubs.net%22%2C%22fields%22%3A%22KDM3A_tf_targets%22%2C%22columnLabel%22%3A%22Gene%20Expression%20Activity%22%2C%22fieldLabel%22%3A%22KDM3A_tf_targets%22%7D%5D&heatmap=%7B%22showWelcome%22:false%7D

FYI @jingchunzhu

**Comment by acthp** [comment]
Fix in v2.87.2
