### ISSUE TITLE
KM plot with empty group

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#54]
I think we should remove groups that is empty.  This will come into
critical play when KM and filter is linked. -- this is the same problem as
there are empty groups in data column before filtering.

attached data for tcga pan-cancer cohort, load to your local xena, go to tcga pan-cancer cohort, filter on this dataset, then do KM, will cause problem
[Archive.zip](https://github.com/acthp/ucsc-xena-client/files/155998/Archive.zip)

**Comment by acthp** [comment]
Not sure about this example. What column do you draw km against?

**Comment by jingchunzhu** [comment]
phenotype -> _cohort column.  Use the attached data in Archive.zip as the filter. Then click KM plot again.

**Comment by acthp** [comment]
Maybe attach a screenshot. When I do this it draws one curve with the samples in the data file. Not sure what else it should do. There are no empty groups in this example.

**Comment by jingchunzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/999493/13552294/03c8da6e-e311-11e5-91c6-2650435e73c9.png)

In one time, I just get this loading screen stays there forever.

And in all other cases, there is no KM popup.

**Comment by acthp** [comment]
Fixed via 4149ce9efb1e3fd4eda5130ea3aed76bcb934c70
