### ISSUE TITLE
TCGA and GDC GISTIC datasets lack agreement

### ISSUE THREAD

**Issue by yesitsjess** [ucscXena/ucsc-xena-client#545]
I've been comparing the TCGA pancan atlas copy number data ("Gistic2_CopyNumber_Gistic2_all_thresholded.by_genes") and the GDC copy number data ("GDC-PANCAN.gistic.tsv") and I find agreement is really low.

So if you take the 10,626 patient samples easily matched between the datasets and look across the 17,551 genes you see really low agreement between the two datasets. 

If we assume any loss from the TCGA (-2 or -1) is equivalent to loss in GDC (-1) and any TCGA gain (+1 or +2) is the same as GDC gain (+1) then median/mean agreement is only 69% using Cohen's kappa (agree() from irr package). 

If we assume it's only high level deletions/amplifications detected by GDC (so use only -2 or +2 from TCGA) we see good agreement (mean/median 94%) but I think that's likely due to the rarity of the event, when you count gene/patient wise you get the following:

-1-1 = 607700
-10 = 229669
0-1 = 5358533
00 = 177301216
01 = 5144245
10 = 629916
11 = 1869537
-11 = 5069
1-1 = 19607

I wondered if anyone could help to explain why this is the case or, alternatively, help to advise on the most reliable dataset to use to detect copy number loss in TCGA patients?

**Comment by maryjgoldman** [comment]
I have followed up on this issue in another email. For reference, other folks may find this paper useful: https://gdc.cancer.gov/about-data/publications/HG38QC
