### ISSUE TITLE
Drop down menus don't close after selecting an option

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#546]
I'm attaching a gif of the functionality. When you click on a drop down menu, it opens to allow you to select an option. After you select an option the drop down menu stays open instead of automatically closing. You have to click outside the drop down menu to close.

![dropdowndoesntclose.gif](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/9c627dee-8360-49f3-95d0-331221c5ef74)

I'm not sure all of the drop down menus this affects but I can get the list if needed. So far I have seen it in the KM plot where you select which type of survival you want to use as well as in the Chart View wizard when you're selecting the column you want to use for a plot.

**Comment by frano-m** [comment]
@maryjgoldman this is ready to re-check thank you!

**Comment by maryjgoldman** [comment]
This looks great!
