### ISSUE TITLE
Can't create a subgroup column

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#547]
You can search for samples but when you create a new subgroup column from your search, the column is 'loading' forever. 

![nosubgroupcolumn.gif](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/e3ec2bee-536c-4271-bf83-9309aa299cb5)

Here is a bookmark of what it should look like after the subgroup column is created in the example in the gif: https://xenabrowser.net/heatmap/?bookmark=4675d4c24f4b61259ed2ec536f38828a

**Comment by frano-m** [comment]
@acthp I'm going to assign this one back to you based on this [slack thread](https://ucsc-gi.slack.com/archives/C03C3STKQN7/p1650605808891649) !! Thank you!

**Comment by acthp** [comment]
Fixed with https://github.com/ucscXena/ucsc-xena-client/commit/3a579b80750620564f0e09fc4eea0ed3bba46d0e
