### ISSUE TITLE
Nav Bar disappears if you navigate away from /heatmap/ page

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#552]
If you click to another part of the application, such as the data hubs or transcript view, and then navigate back to the /heatmap/ page, the nav bar doesn't show.

![navBarDisappears.gif](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/fc6e91ef-aec4-4880-a2aa-b85050341fcf)

**Comment by NoopDog** [comment]
Thanks, @maryjgoldman will take a look. D

**Comment by frano-m** [comment]
@acthp I'm assigning this back to you based on this slack thread (see https://ucsc-gi.slack.com/archives/C03C3STKQN7/p1655312183877609?thread_ts=1655268519.581179&cid=C03C3STKQN7). Thank you!

**Comment by NoopDog** [comment]
@frano-m I presume this is part of the MUI upgrade and can be closed? If this is the case, can you close this? Thanks! D
