### ISSUE TITLE
Going from 'gene average' view to 'detailed view' when column is clustered results in a gray column

### ISSUE THREAD

**Issue by maryjgoldman** [ucscXena/ucsc-xena-client#572]
This only applies gene column that has subcolumns (for instance, for an exon or transcript expression dataset). 

Steps to reproduce:
1. Use the column menu to cluster the subcolumns
2. Use the column menu to view the gene average
3. Use the column menu to view the detailed view
--> see gray 'blank' column

What it looks like now:
![bugWithDetailedViewAndClustering.gif](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/b02f6608-9905-4b5a-9d62-6f1f6b5450ea)

What it should look like:
![correctDetailedViewClustering.gif](https://images.zenhubusercontent.com/5b34f42a89c1fc1ffe8ce9a6/21b5561b-e1e0-4e75-8915-cdd05d78a4f3)

Bookmark to view: https://cc.xenabrowser.net/heatmap/?bookmark=cd6d8adead7d720fea7df197dc807147

**Comment by acthp** [comment]
I believe this is already fixed on master with https://github.com/ucscXena/ucsc-xena-client/commit/37ee87b0de7a455780a584857507214e5b46826a

We can review this after the merge.
