### ISSUE TITLE
labels (for zoom view) needs only 3 significant digits.

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#64]
There are too many significant digits. 
![image](https://cloud.githubusercontent.com/assets/999493/13583707/c145c1fe-e467-11e5-99ca-47ab0306942d.png)

**Comment by maryjgoldman** [comment]
@jingchunzhu Did you close this because it is already out on production or because you fixed it right now? I can't find a test case for this
