### ISSUE TITLE
Implement UI Updates to the Visualization Section 

### ISSUE THREAD

**Issue by NoopDog** [ucscXena/ucsc-xena-client#667]
- [ ] Update selectors for making new graphs and selecting grant types and options as per UI mocks .
- [ ] Review initial proposals with the team and process any feedback/changes.
- [ ] Ticket out update detail

**Comment by frano-m** [comment]
See [mocks](https://www.figma.com/file/CikQhnq8fvMKPRbg8Ow5PT/Xena-Functional-Gemonics-Explorer?type=design&node-id=428-22196&mode=design&t=YRydLFxEtysyznsW-4).

**Comment by NoopDog** [comment]
Complete!
