### ISSUE TITLE
Error Screen after adding a Column w/ Mutation Dataset + invalid gene

### ISSUE THREAD

**Issue by achang28** [ucscXena/ucsc-xena-client#68]
A split second after adding a column for the following parameters will yield the red error screen below:
Cohort:  "**TCGA Esophageal Cancer**"
Dataset:  "**somatic mutation SNPs and small INDELs (ucsc automated vcf)**"
Gene: '**xxx**'

![errorscreen](https://cloud.githubusercontent.com/assets/3760499/13623917/f43f0bae-e55e-11e5-83b8-253a264b2b98.png)

**Comment by jingchunzhu** [comment]
fixed c7d0bd0
