### ISSUE TITLE
reducing the drawing time of mutationVector data

### ISSUE THREAD

**Issue by jingchunzhu** [ucscXena/ucsc-xena-client#69]
- for genes with few mutations in the TCGA Pan-cancer mutation data (e.g. gene=TCAP) , it still takes a while to draw.

**Comment by acthp** [comment]
Effort is probably better spent reducing the drawing time. The largest limiting factor in this case is that the server is returning all rows of the ```sampleID``` field, which burns time in both the server and client. On the client, with the total draw time being 15s, 7s is spent in ```_.uniq``` dropping the duplicate sampleIDs. The response takes about 5s to arrive, most of which is probably the server encoding all those sampleIDs. So, close to 80% of the wait time is avoidable by fixing the server.

**Comment by acthp** [comment]
I'm going to resolve this by reverting to an earlier version of the query, which will only take a couple minutes. Will update the server as a longer-term solution.

**Comment by jingchunzhu** [comment]
Large number of intron mutations (mutations in general annotated by the gene name by not going to make it to the view anyway) are still bying retrieved --  maybe querying by the genomic range in of the transcript (the array of arrays), therefore you will not pull the large number of intron mutations. -Jing
