### ISSUE TITLE
handle eot files

### ISSUE THREAD

**Issue by acthp** [ucscXena/ucsc-xena-client#74]
The django connector does not serve eot. We've had one client see a server 500 requesting the eot file.

```
 Internal Server Error: /proj/site/xena/f4769f9bdb7466be65088239c12046d1.eot
```

This is a font file. I'm not sure which of our dependencies is generating it.

**Comment by souravsingh** [comment]
@acthp I am interested in investigating the issue. My thoughts is the error is due to the the rendering of the font in a specific browser( cannot say which one without investigating).

**Comment by acthp** [comment]
I suspect this is no longer an issue. We previously hosted xena on a domain that was served by a python django app, and the view for serving xena assets was not handling eot files correctly.  We're now hosted on aws and serve the files from apache.

If we can't identify an example of a server error with an eot file, we should close this.
